name: src_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.1
  audioplayers: ^6.0.0            # Upgraded
  flip_card: ^0.7.0
  just_audio: ^0.9.36
  intl: ^0.19.0
  share_plus: ^10.0.3

  app_links: ^6.3.3               # Thay thế uni_links
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.0.0
  go_router: ^13.0.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0             # Upgraded để fix lỗi v1 embedding
  http_parser: ^4.0.2
  pdf: ^3.10.8
  printing: ^5.11.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#4CAF50"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
        - asset: assets/fonts/Inter-ItalicVariableFont.ttf
          style: italic